Repository camptocamp/c2cwsgiutils, pull requests merged in 2022-11, with the labels that each got.

#1608 Fix repository in workflow used to delete old workflow runs
  .github/workflows/delete-old-workflows-run.yaml
Labels: chore

#1612 Create or update a Poetry group for Renovate
  .github/renovate.json5
  acceptance_tests/app/requirements.txt
  requirements.txt
Labels: chore

#1621 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#1622 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#1623 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#1624 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#1625 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#1615 Fix publish
  ci/requirements.txt
  requirements.txt
Labels: bug

#1628 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
Labels: chore

#1629 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
  .github/workflows/dependabot-auto-merge.yaml
Labels: chore

#1643 Replace deprecated --dev with --with=dev
  Dockerfile
  Makefile
Labels: chore

#1644 Remove pip upgrading to the latest version
  .github/workflows/main.yaml
Labels: chore

#1645 Remove set local environment variables
  Dockerfile
Labels: chore

#1649 Upgrade deprecated set-output commands
  .github/workflows/changelog.yaml
Labels: chore

#1659 Remove unwanted audit issues, fix CVE
  ci/config.yaml
  requirements.txt
Labels: backport release_4

#1663 Sqlalchemylogger: fix readme
  c2cwsgiutils/sqlalchemylogger/README.md
Labels: documentation

#1646 Set the used Python version for Poetry to one minor version
  acceptance_tests/app/pyproject.toml
Labels: chore

#1668 Removes poetry-core dependency
  requirements.txt
Labels: chore
