Repository camptocamp/c2cwsgiutils, pull requests merged in 2023-12, with the labels that each got.

#2067 Docker compose is not compatible with Docker 8
  scripts/install-docker
Labels: backport master, backport 5.0, backport 5.1, backport 5.2, backport 6.0

#2076 Fix doc - prometheus port var env name
  README.md
Labels: backport 6.0

#2078 Improve image check
  c2cwsgiutils/acceptance/image.py
Labels: backport master

#2080 Image test fix...
  c2cwsgiutils/acceptance/image.py
  c2cwsgiutils/acceptance/screenshot.js
Labels: backport master
