Repository camptocamp/c2cwsgiutils, pull requests merged in 2024-11, with the labels that each got.

#2496 Ignore CVE
  .snyk
Labels: backport 5.0

#2514 README: Remove misleading info about version
  README.md
Labels: backport 6.0, backport 6.1

#2531 Bump to version 5.0.4
  setup.py
Labels: chore

#2532 Bump to version 5.1.9
  setup.py
Labels: chore

#2537 Merge the filters
  c2cwsgiutils/debug/_views.py
Labels: backport master

#2539 Add some explain in the c2c page
  acceptance_tests/out/tests/c2c-auth-dark.expected.png
  acceptance_tests/out/tests/c2c-auth.expected.png
  acceptance_tests/out/tests/c2c.expected.png
  acceptance_tests/out/tests/test_image_check.py
  c2c-auth-dark.actual-masked.png
  c2c-auth.actual-masked.png
  c2c.actual-masked.png
  c2cwsgiutils/debug/_listeners.py
  c2cwsgiutils/debug/_views.py
  c2cwsgiutils/index.py
  c2cwsgiutils/templates/index.html.mako
Labels: backport master
